export const statCards = [
  {
    label: "Users",
    value: "1,245",
    change: "+4.2%",
    icon: "Users",
    color: "from-indigo-500 via-purple-500 to-pink-500",
  },
  {
    label: "Revenue",
    value: "$23,400",
    change: "+2.1%",
    icon: "DollarSign",
    color: "from-emerald-500 to-teal-600",
  },
  {
    label: "Active Sessions",
    value: "312",
    change: "-1.3%",
    icon: "Activity",
    color: "from-rose-500 to-amber-500",
  },
  {
    label: "Errors",
    value: "7",
    change: "+0.5%",
    icon: "AlertTriangle",
    color: "from-slate-900 to-slate-800 dark:from-zinc-950 dark:to-zinc-900",
  },
];

export const tableData = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "Admin",
    status: "Active",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    role: "Editor",
    status: "Active",
  },
  {
    id: 3,
    name: "Carol Lee",
    email: "carol.lee@example.com",
    role: "Viewer",
    status: "Inactive",
  },
  {
    id: 4,
    name: "David Kim",
    email: "david.kim@example.com",
    role: "Admin",
    status: "Active",
  },
  {
    id: 5,
    name: "Eva Green",
    email: "eva.green@example.com",
    role: "Editor",
    status: "Active",
  },
  {
    id: 6,
    name: "Frank Moore",
    email: "frank.moore@example.com",
    role: "Viewer",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Grace Lee",
    email: "grace.lee@example.com",
    role: "Admin",
    status: "Active",
  },
  {
    id: 8,
    name: "Henry Ford",
    email: "henry.ford@example.com",
    role: "Editor",
    status: "Active",
  },
  {
    id: 9,
    name: "Ivy Chen",
    email: "ivy.chen@example.com",
    role: "Viewer",
    status: "Inactive",
  },
  {
    id: 10,
    name: "Jack White",
    email: "jack.white@example.com",
    role: "Admin",
    status: "Active",
  },
  {
    id: 11,
    name: "Karen Black",
    email: "karen.black@example.com",
    role: "Editor",
    status: "Active",
  },
  {
    id: 12,
    name: "Leo Brown",
    email: "leo.brown@example.com",
    role: "Viewer",
    status: "Inactive",
  },
];
